base_url?=https://webthing-iotjs-robot.glitch.me/properties/

test:
	curl -X PUT -d '{ "Torso": -90 }'  https://webthing-iotjs-robot.glitch.me/properties/Torso
	curl -X PUT -d '{ "Shoulder": -90 }'  https://webthing-iotjs-robot.glitch.me/properties/Shoulder
	curl -X PUT -d '{ "Arm": -90 }'  https://webthing-iotjs-robot.glitch.me/properties/Arm
	curl -X PUT -d '{ "Hand": -90 }'  https://webthing-iotjs-robot.glitch.me/properties/Hand

	curl -X PUT -d '{ "Torso": 0 }'  https://webthing-iotjs-robot.glitch.me/properties/Torso
	curl -X PUT -d '{ "Shoulder": 0 }'  https://webthing-iotjs-robot.glitch.me/properties/Shoulder
	curl -X PUT -d '{ "Arm": 0 }'  https://webthing-iotjs-robot.glitch.me/properties/Arm
	curl -X PUT -d '{ "Hand": 0 }'  https://webthing-iotjs-robot.glitch.me/properties/Hand


	curl -X PUT -d '{ "Torso": 45 }'  https://webthing-iotjs-robot.glitch.me/properties/Torso
	curl -X PUT -d '{ "Shoulder": 45 }'  https://webthing-iotjs-robot.glitch.me/properties/Shoulder
	curl -X PUT -d '{ "Arm": 45 }'  https://webthing-iotjs-robot.glitch.me/properties/Arm
	curl -X PUT -d '{ "Hand": 45 }'  https://webthing-iotjs-robot.glitch.me/properties/Hand

	curl -X PUT -d '{ "Torso": 90 }'  https://webthing-iotjs-robot.glitch.me/properties/Torso
	curl -X PUT -d '{ "Shoulder": 90 }'  https://webthing-iotjs-robot.glitch.me/properties/Shoulder
	curl -X PUT -d '{ "Arm": 90 }'  https://webthing-iotjs-robot.glitch.me/properties/Arm
	curl -X PUT -d '{ "Hand": 90 }'  https://webthing-iotjs-robot.glitch.me/properties/Hand



stable:
	curl -X PUT -d '{ "Torso": -45 }'  https://webthing-iotjs-robot.glitch.me/properties/Torso
	curl -X PUT -d '{ "Shoulder": 15 }'  https://webthing-iotjs-robot.glitch.me/properties/Shoulder
	curl -X PUT -d '{ "Arm": 85 }'  https://webthing-iotjs-robot.glitch.me/properties/Arm
	curl -X PUT -d '{ "Hand": 0 }'  https://webthing-iotjs-robot.glitch.me/properties/Hand


